### DISCUSSION TITLE
0.0.1

### DISCUSSION THREAD

**Discussion by YSHgroup** [YSHgroup/vue3-fullcalendar-bootstrap#3] [Announcements]
First deploy.

<hr /><em>This discussion was created from the release <a href='https://github.com/YSHgroup/vue3-fullcalendar-bootstrap/releases/tag/0.0.1'>0.0.1</a>.</em>

**Comment by Infinity-chakra** [comment]
@YSHgroup, What is the git workflow CLI to create release automatically whenever push to main on your side?

**Reply by YSHgroup** [reply]
I think the current code is correct and simply and correctly, try with the following code line in the create-release.yml file.

```yaml
name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get latest version
        id: get_version
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          version=$(echo $latest_tag | sed 's/v//')
          IFS='.' read -ra version_parts <<< "$version"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=$((${version_parts[2]}+1))
          new_version="$major.$minor.$patch"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.new_version }}
          release_name: Release ${{ steps.get_version.outputs.new_version }}
          body: |
            This is an automated release created on push to the main branch.
          draft: false
          prerelease: false
```
